---
 - hosts: "{{ variable_host | default('hostname') }}"
   become: yes
   become_user: "{{ default_user }}"
   tasks:
     - name: Make sure the directory exist
       file:
         path: "/home/{{default_user}}/.config/systemd/user"
         state: directory
     - name: Make the systemd configuration for django-demo
       copy:
         src: django-demo.service.j2
         dest: "/home/{{default_user}}/.config/systemd/user/django-demo.service"
         force: yes
     - name: Start django-demo.service and enable on start on boot
       systemd:
         name: django-demo
         scope: user
         state: started
         enabled: yes
         daemon_reload: yes
